# Generated by Django 3.2.9 on 2021-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSecrets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=120)),
                ('app_id', models.CharField(blank=True, max_length=120, null=True)),
                ('app_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('access_token', models.CharField(max_length=256)),
            ],
        ),
    ]
